[slides]
talks = [
    { name = "How Rust compiles", location = "EuroRust Paris 2025", date = "2025-10-10", recording = "https://youtu.be/G1g6Me1FHmE" },
    { name = "How to contribute to the Rust project", location = "Rust Zürisee", date = "2024-01-17", recording = "https://www.youtube.com/live/Ptl6kOZM9GI?t=740" },
]
